const tempData = [
  {
    id: 1,
    title: 'Апартаменты на Вавилова',
    district: 'Центральный',
    address: 'ул.Вавилова, д.27',
    area: 120,
    bedroom: 2,
    image: 'https://image.freepik.com/free-photo/minimalist-dining-living-room-design_23-2148291620.jpg',
    guests: 4,
    price: {
      short: 3990,
      middle: 3190,
      long: 2290,
    },
    bedrooms: 2,
    parking: 'private',
    district: 'Центральный',
    fitness: false,
    cleaning: true,
    floor: 7,
    kitchen: true,
  },
  {
    id: 2,
    title: 'Апартаменты на Луговой',
    district: 'Восточный',
    address: 'ул.Луговая, д.44',
    area: 65,
    bedroom: 1,
    image: 'https://image.freepik.com/free-photo/front-view-chair-room-with-plant-decoration_23-2148560899.jpg',
    guests: 3,
    price: {
      short: 3190,
      middle: 2190,
      long: 1290,
    },
    bedrooms: 1,
    parking: 'public',
    district: 'Заречье',
    fitness: false,
    cleaning: false,
    floor: 3,
    kitchen: false,
  },
  {
    id: 3,
    title: 'Апартаменты на Вавилова',
    district: 'Центральный',
    address: 'ул.Вавилова, д.27',
    area: 120,
    bedroom: 2,
    image: 'https://image.freepik.com/free-photo/minimalist-dining-living-room-design_23-2148291620.jpg',
    guests: 6,
    price: {
      short: 4990,
      middle: 4190,
      long: 3290,
    },
    bedrooms: 3,
    parking: 'private',
    district: 'Центральный',
    fitness: true,
    cleaning: true,
    floor: 14,
    kitchen: true,
  },
  {
    id: 4,
    title: 'Апартаменты на Луговой',
    district: 'Восточный',
    address: 'ул.Луговая, д.44',
    area: 65,
    bedroom: 1,
    image: 'https://image.freepik.com/free-photo/front-view-chair-room-with-plant-decoration_23-2148560899.jpg',
    guests: 2,
    price: {
      short: 1990,
      middle: 1190,
      long: 990,
    },
    bedrooms: 0,
    parking: 'public',
    district: 'Свердловский',
    fitness: false,
    cleaning: false,
    floor: 1,
    kitchen: false,
  },
  {
    id: 5,
    title: 'Апартаменты на Вавилова',
    district: 'Центральный',
    address: 'ул.Вавилова, д.27',
    area: 120,
    bedroom: 2,
    image: 'https://image.freepik.com/free-photo/minimalist-dining-living-room-design_23-2148291620.jpg',
    guests: 4,
    price: {
      short: 4990,
      middle: 3990,
      long: 2990,
    },
    bedrooms: 3,
    parking: 'public',
    district: 'Ленинский',
    fitness: true,
    cleaning: true,
    floor: 4,
    kitchen: true,
  },
  {
    id: 6,
    title: 'Апартаменты на Луговой',
    district: 'Восточный',
    address: 'ул.Луговая, д.44',
    area: 65,
    bedroom: 1,
    image: 'https://image.freepik.com/free-photo/front-view-chair-room-with-plant-decoration_23-2148560899.jpg',
    guests: 3,
    price: {
      short: 2990,
      middle: 2190,
      long: 1290,
    },
    bedrooms: 1,
    parking: 'private',
    district: 'Центральный',
    fitness: false,
    cleaning: false,
    floor: 11,
    kitchen: true,
  },
];

export { tempData };
